# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

if [ -f ~/.git-prompt.sh ]; then
    . ~/.git-prompt.sh
fi

if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# Alias List
alias ll='ls -lh'
alias l='ls -lh'
alias md='mkdir'
alias o='open . &'
alias ,='cd ..'
alias clear='echo use Control + l'

# tmux
alias tmux='tmux -2'
alias tma='tmux -2 attach -d -t'
alias tml='tmux list-sessions'

# Git
# alias g='git status'
# alias gs='git show'
# alias gl='git log'
# alias gb='git branch -a'
# alias gd='git diff'
# alias ga='git add'
# alias gc='git commit -m'
# alias gca='git commit -v -a'
# alias gprom='git pull --rebase origin master'
# alias gpom='git push origin master'
# alias grh='git reset --hard'

# Tell ls to be colorful
export CLICOLOR=1
export LSCOLORS=Exfxcxdxbxegedabagacad

# Tell grep to highlight matches
export GREP_OPTIONS='--color=auto'

# User specific aliases and functions

# Ignore case for input
bind 'set completion-ignore-case on'
