# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

setopt allexport
EDITOR=vim;

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="robbyrussell"
# ZSH_THEME="agnoster"
ZSH_THEME="terminalparty"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git st stt)

source $ZSH/oh-my-zsh.sh

generalPath="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
windowsPath="/c/Windows/System32:/c/Program Files/Perforce"

export PATH=$HOME/bin:$generalPath:$windowsPath:/opt/boxen/nodenv/versions/v0.10/bin

[ -e "${HOME}/.zsh_aliases" ] && source "${HOME}/.zsh_aliases"
[ -e "${HOME}/.zshrc_local" ] && source "${HOME}/.zshrc_local"

PROMPT='${PWD/#$HOME/~}%{$fg_bold[green]%}>%{$fg[white]%} '
#RPROMPT=''
#RPROMPT=$'$(git_super_status)'
# PROMPT=$'%{$fg_bold[white]%}%M %{$fg_bold[red]%}➜ %{$fg_bold[green]%}%p %{$fg[cyan]%}%c %{$fg_bold[blue]%}%{$fg_bold[blue]%} % %{$reset_color%}'

# Dotfiles update
source ~/dotfiles/tools/check_for_upgrade.sh

# whiteboard () {
#     convert $1 -morphology Convolve DoG:15,100,0 -negate -normalize -blur 0x1 -channel RBG -level 60%,91%,0.1 $2
# }
#
. /opt/boxen/env.sh

eval "$(gulp --completion=zsh)"
eval "$(skypeit --completion=zsh)"
eval "$(tog completion zsh)"

# thanks to http://murphymac.com/tree-command-for-mac/
alias tree='find . -print | sed -e "s;[^/]*/;|____;g;s;____|; |;g"'
alias gdiff='git difftool -y --extcmd icdiff | less'
alias mou='open /Applications/Mou.app'
. ~/commandAllThingsProfile.sh
